aws/aws-iot-device-sdk-python-v2

awsiot/iotjobs.py, awsiot/iotshadow.py, samples/jobs.py, samples/shadow.py
Operation names are no longer abbreviated.
=> Fine-tuning names in service models.

awsiot/__init__.py, awsiot/iotjobs.py, awsiot/iotshadow.py, samples/jobs.py, samples/shadow.py
Unsubscribe for service clients.
=> Unsubscribe()

README.md, awsiot/__init__.py, samples/jobs.py, samples/pubsub.py, samples/shadow.py
The shadow sample got more changes than were strictly necessary, to look more like the jobs sample.
=> React to API changes in aws-crt-python v0.2.0

awsiot/__init__.py, samples/jobs.py, samples/pubsub.py, samples/shadow.py
=> Fix bug where bytes were passed to json.loads()

README.md, awsiot/__init__.py, awsiot/greengrass_discovery.py, samples/basic_discovery.py, samples/jobs.py, samples/pubsub.py, samples/shadow.py, setup.py
Update to `awscrt` 0.3.1
Adapt to API changes:
- HTTP API:
- had an extreme makeover, but that only affects the implementation of Greengrass Discovery, not its API.
- MQTT API:
- The Future returned by `subscribe()` now contains a `QoS`. It used to contain `None`.
- `on_connection_interrupted` and `on_connection_resumed` callbacks have an extra `connection` argument.
- IO API:
- `override_default_trust_store_from_path()` arguments renamed
=> use latest awscrt

continuous-delivery/test_prod_pypi.yml, continuous-delivery/test_test_pypi.yml, setup.py
=> Fix deployment scripts

continuous-delivery/publish_to_test_pypi.yml, continuous-delivery/test_prod_pypi.yml, continuous-delivery/test_test_pypi.yml, continuous-delivery/wait-for-pypi.py, setup.py
Also incorporate `wait-for-pypi.py` into continuous-delivery pipeline, which is copy/pasted from awscrt.
=> Awscrt 0.5.6

continuous-delivery/test_version_exists, setup.py
Update `awscrt` to version 0.5.11. Improvements include:
- MQTT improvements
- Fix `on_connection_resumed` callback's `return_code` argument.
- Reduce default duration between MQTT keep-alive pings.
- Drop connection if server CONNACK takes too long.
- Fix crash-on-exit which was common on Windows.
- GCC 8 support
=> Update awscrt to 0.5.11

continuous-delivery/test_version_exists
This stage never explicitly had python2, it only worked because the old docker images happened to have python2. Broken when we upgrade images.
=> Fix deployment script that broke in new docker image

.github/ISSUE_TEMPLATE/---bug-report.md, .github/workflows/stale-issue.yml
NA
Added a new github action it will:
- check for ancient issues (more than a year with no update) : it will message and mark for closing soon.
- check for stale issues (more than a week with no update) : same but different message prompting for update.
- check for closing soon label and close issues that have not been updated for 3 days after labeled.
=> added a github action to close stale issues

README.md
Raspberry Pi occurs an error at installing awsiotsdk
This changes show the step to install AWS IoT Device SDK Python on Raspberry Pi (buster)
=> add install step for Raspberry Pi

awsiot/__init__.py
*Issue #, if available:* N/A
I was getting the following error when trying to unsubscribe from a topic using an instance of IotShadowClient:
```
...
File "/Users/josh/.local/share/virtualenvs/test-aws-iot-q2iEHued/lib/python3.7/site-packages/awsiot/__init__.py", line 62, in unsubscribe
unsub_future.add_done_callback(on_unsuback)
AttributeError: 'tuple' object has no attribute 'add_done_callback'
```
The return value of `mqtt_connection.unsubscribe()` wasn't being unpacked so `add_done_callback()` was being called on the tuple instead of the future. This change just unpacks that tuple.
=> Fixed MqttServiceClient unsubscribe

README.md, awsiot/iotidentity.py, samples/fleetprovisioning.py
IotIdentityClient for Fleet Provisioning using CreateKeysAndCertificate and CreateCertificateFromCsr. A sample application for fleet provisioning supporting both ways.
=> Fleetprovisioning

README.md, samples/README.md, samples/basic_discovery.py, samples/fleetprovisioning.py, samples/jobs.py, samples/pubsub.py, samples/shadow.py
ISSUE:
Currently, the "Getting Started Kit" vended by the IoT console vends a policy that doesn't match the strings used by any V2 SDK samples. So they fail right off the bat 😢
SOLUTION:
Let's get all the V2 SDKs using the same strings, then we can create a policy to fit them all. I'd like to put wildcards in the new policy so users can toy around a little bit, but include the word "test" everywhere so they feel inclined to change it before they ship.
Also, let's get all the samples putting randomness into the client-id, since colliding IDs are a frequent source of confusion.
=> All V2 SDK samples can share policies.

samples/README.md
* Initial attempt at giving more detailed instructions with respect to fleet provisioning.  We have multiple issues asking about how to get it set up.
=> First draft provisioning details

setup.py
from 0.6.2 to 0.8.0
includes:
- API CHANGE: awscrt.auth.AwsSigningConfig.signed_body_value is now a string instead of an enum.
- API CHANGE: Added check for iOS platform
- BUGFIX: websocket no longer hangs if CLOSE frame cannot be sent.
- BUGFIX: Fixes a crash when shutting down an mqtt connection with an incomplete request with no callback from aws-c-mqtt
=> update awscrt to 0.8.0

NOTICE, README.md, awsiot/__init__.py, awsiot/greengrass_discovery.py, builder.json, docsrc/conf.py, docsrc/index.rst, samples/README.md, samples/fleetprovisioning.py, samples/jobs.py, samples/pubsub.py, samples/shadow.py, setup.py, test/test_samples.py, utils/parse_cert_set_result.py
Python 2's end-of-life date was Jan 1 2020.
=> Remove support for python 2

continuous-delivery/publish_to_prod_pypi.yml, continuous-delivery/publish_to_test_pypi.yml
We no longer support Python 2.
=> Stop marking wheels as "universal".

README.md
*Issue #120*
The location of the file is at the same level of the readme.md so remove the "master" directory name in the link.
=> Fix the wrong link

continuous-delivery/test_prod_pypi.yml, continuous-delivery/test_test_pypi.yml
apparently, even though `pip search` has just confirmed that the brand new version exists, you still need to tell `pip install` to avoid its local cache
=> don't use pip cache when installing brand new version

samples/README.md, setup.py
N/A
We should be using the OSI license attribute in the classifier, and the license attribute should match that.
=> Add proper license attribute per OSI license

README.md
**Issue**
#169 
User encountered `fatal error: Python.h: No such file or directory` when installing from source.
**Description of changes:**
Update README to mention that python headers need to be installed. Also remove openssl installation instructions.
=> Update "Installation Issues" in README

awsiot/eventstreamrpc.py, setup.py
*Issue #:* https://github.com/aws/aws-iot-device-sdk-python-v2/issues/149
- Update awscrt to get fixes for leaking headers and leaking connection
- Break circular references in evenstreamrpc so garbage collector can clean them up
=> Fix memory leaks in greengrasscoreipc

samples/shadow.py
- Wait until we've subscribed to all "reponse" topics before subscribing to "delta". This fixes a bug where a "delta" that fires right away, results in a "update-request" being sent, but we're not yet subscrubed to the "update-response".
- Connect with clean_session=True. This avoids weird stuff where we get responses to old requests immediately upon subscribing.
=> Fix bugs in shadow sample.

setup.py
* On Windows, always perform an SNI check even with an overridden root CA
* On Windows, properly honor the verify_peer = false option
* Fix instability with raspberry PI and input stream seeking by doing a better job of modeling file seek offset type and size.
=> Update to CRT 0.11.22

samples/shadow.py
**Issue:** MQTT is not a request/response protocol.  Messages for the Shadow service have a "client token" field to help users correlate "request" messages to "response" messages, but this sample script wasn't using the token field. This led to confusion when running Device Advisor tests which send several `shadow/update` "request" messages during setup. The sample was receiving the `shadow/update/accepted` "response" messages unexpectedly leading to crashes.
**Changes:** Set token on all "request" messages. Ignore any "response" message with an unexpected token.
=> Use token to correlate "requests" and "responses".

samples/pubsub.py
if the mqtt payload is a string the AWS MQTT test client shows a "Message cannot be displayed in specified format." warning.
Changed the payload to json to prevent the aforementioned warning/error.
=> Json message

samples/basic_discovery.py, samples/fleetprovisioning.py, samples/jobs.py, samples/pubsub.py, samples/shadow.py
*Issue #, if available: #216
*Description of changes: Modify default keep-alive interval of samples from 6 seconds to 30 seconds.
=> Modify default keep_alive_secs of samples

awsiot/greengrasscoreipc/client.py, awsiot/greengrasscoreipc/model.py
=> feat: add greengrass APIs for resource management (#7)

setup.py
Update to awscrt 0.12.0. This fixes the issue where "override_default_trust_store" functions did not actually override the system trust store on Linux and Apple platforms.
=> Fix CA override functions

samples/README.md
Update the Greengrass discovery sample README to add links to Greengrass V2 documentation, because Greengrass V2 now supports client devices and Greengrass discovery. Previously, the README included only a link to Greengrass V1 documentation.
Add links to Greengrass V2 documentation.
=> Add Greengrass V2 documentation links to Greengrass discovery sample README

awsiot/mqtt_connection_builder.py, samples/README.md, samples/pkcs11_pubsub.py, setup.py
- Update to latest `aws-crt-python`, which exposes PKCS#11 functionality (see https://github.com/awslabs/aws-crt-python/pull/323)
- Add `pkcs11_pubsub.py` sample, demonstrating an MQTT connection where the private key is stored in PKCS#11 token.
- Add docs for sample
=> Support PKCS#11 for mutual TLS on Unix platforms

.gitignore, test/test_ggv2.py
=> Add test for GGV2 client using mocked rpc connection

awsiot/eventstreamrpc.py, awsiot/greengrasscoreipc/clientv2.py
Adds close method to rpc Client and adds and uses that close method in the Greengrass V2 client.
=> fix: add close method to rpc client to close the connection

awsiot/iotshadow.py, samples/shadow.py
Closes #114
Adjusted the code for the ShadowState class so passing `None` is a valid input. This allows for clearing the `reported` or `desired` properties entirely in a method similar to the V1 SDK.
This PR makes the following changes:
* Adjusts the `iotshadow.py` file to allow for passing `none`.
* Now the `desired` and `reported` fields are set to empty dictionaries on initialization rather than being set to `None`.
* The code for sending the package check to see if `desired` or `reported` are equal to empty dictionaries instead of `None`.
* Adjusted the shadow sample
* When you type `none`, it will now set the property to a Python `none` object, clearing the property with the shadow sample name.
* When you type `clear_shadow`, it will …
=> Rebuilt shadow bindings and updated shadow sample to show how to clear properties

PREREQUISITES.md, README.md
Added install instructions to the README for Python and dependencies, adding links to the C++ repository for things like CMake and C compilers. Specific install instructions were added for things specific to this repository, like Python.
____________
*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.*
=> README Adjustment

continuous-delivery/test_prod_pypi.yml, continuous-delivery/test_test_pypi.yml
Fixes the continuous delivery failing due to the samples being passed the wrong arguments when I updated the argument names.
________
=> Fix continuous delivery using wrong argument names in test

continuous-delivery/test_prod_pypi.yml, continuous-delivery/test_test_pypi.yml
Another argument fix. I thought I got them all but missed `-v` now being `--verbosity` (I thought `-v` still worked, but apparently not...)
______________
=> Additional continuous delivery fix

setup.py
functionality comes from updated awcrt dependency.
**Issue #:**
https://github.com/aws/aws-iot-device-sdk-python-v2/issues/295
Co-authored-by: @JamieHunter 
=> Add ECC support for PKCS#11

codebuild/samples/linux-smoke-tests.yml, codebuild/samples/pkcs11-connect-linux.sh, samples/command_line_utils.py, samples/pkcs11_connect.py
**Issue:**
pkcs11_connect.py sample is broken: https://github.com/aws/aws-iot-device-sdk-python-v2/issues/309
**Diagnosis:**
This wasn't tested as part of CI, so a trivial accident while refactoring the samples wasn't caught.
**Changes:**
Add missing `return` statement. Also, add pkcs11_connect.py sample to our CI so we catch any future breaks.
=> Fix pkcs11_connect.py sample

setup.py
https://github.com/aws/aws-iot-device-sdk-python-v2/issues/286
Use latest version of awscrt, which has wheels that work properly on M1 macs
=> Improved support for Apple Silicon aka M1 aka arm64 aka Universal2

awsiot/mqtt_connection_builder.py, codebuild/samples/connect-auth-linux.sh, codebuild/samples/linux-smoke-tests.yml, samples/README.md, samples/command_line_utils.py, samples/custom_authorizer_connect.py
Adds a custom authorizer sample, following the same format as the Java V2 custom authorizer sample. 
Also modifies the MQTT connection builder code so it is possible to easily make a custom authorizer connection, and modifies adding the SDK metrics to the username so it correctly adds it to the end of the username if the username is a query string.
__________
=> Added custom authorizer sample

setup.py
The recent arm64 support for awscrt isn't working 100%.
I get the following with 0.13.11:
```
building '_awscrt' extension
ld: warning: ignoring file build/temp.macosx-10.14-arm64-3.8/deps/install/lib/libaws-c-mqtt.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file build/temp.macosx-10.14-arm64-3.8/deps/install/lib/libaws-c-http.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file build/temp.macosx-10.14-arm64-3.8/deps/install/lib/libaws-c-s3.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file build/temp.macosx-10.14-arm64-3.8/deps/install/lib/libaws-c-auth.a, building for macOS-x86_64 but …
```
=> further awscrt bump for arm64 support

awsiot/greengrasscoreipc/client.py, awsiot/greengrasscoreipc/clientv2.py, awsiot/greengrasscoreipc/model.py
Greengrass V2 IPC model for new API PutComponentMetric
=> Update Greengrass V2 IPC model for PutComponentMetric operation

awsiot/mqtt_connection_builder.py
Mirror of #331 - but merged with latest version of main and run through CI. Tested with custom authorizer sample with Python 3.7 to make sure it works with versions prior to 3.8+.
_________
=> Avoid warnings for using 'is' with literals in python 3.8+ (mirror)

awsiot/mqtt_connection_builder.py
Closes #340 
Fixes `kwargs` being passed as a single object rather than being unpacked when passed as an argument.
_____________
=> Fix kwargs in default builder not being unpacked correctly

docsrc/conf.py, setup.py
Pick up aws-c-common fix for dlopen usage from mac
=> update CRT to latest

continuous-delivery/publish_to_prod_pypi.yml
Changes the PyPi release to use a IoT SDK specific token from secrets rather than reusing the CRT one.
__________
=> Fix PyPi release to use IoT specific token

samples/README.md, samples/shadow.py
Fixes #360 
Renames `input` to `cli_input` in the CI part of the Shadow sample so it does not override the `input()` function in the non-CLI part of the Shadow sample. Also fixes the `README` showing the `thing_name` argument as `thing-name`.
_________
=> Fix the non-CLI code path for Shadow sample

.gitignore, setup.py
- Update to latest crt-python lib to introduce MacOS ECC key support
- Add .vscode to .gitignore 
=> Update to latest crt lib to add Mac ECC key support

awsiot/greengrass_discovery.py, samples/basic_discovery.py
#376
Exposes settings needed to allow support for proxy options in the Greengrass discovery client. Also adjusts sample to take proxy host and port settings so it functions the same way as the Java sample.
_____________
=> Add proxy support to Greengrass Discovery

.github/workflows/release.yml, utils/publish-release.sh
Fixes a super minor mistake in the release YAML. In my testing repository I had the environment variable as `GH_TOKEN` but in this repository (and the others) I renamed it to `GITHUB_TOKEN` but forgot to change it in the YAML 🤦
__________
=> Fix minor mistake in release YAML

awsiot/mqtt5_client_builder.py
Clone of https://github.com/aws/aws-iot-device-sdk-python-v2/pull/398
=> Fix kwargs usage in mqtt5 builder default constructor

.github/workflows/ci.yml, .github/workflows/ci_run_cognito_connect_cfg.json, documents/MQTT5_Userguide.md, samples/README.md, samples/cognito_connect.py, samples/command_line_utils.py
Adds a sample for showing how to connect to Cognito using the CognitoCredentialsProvider, adjusts the README to include how to setup and run the sample, and adjusts CI to run new the Cognito sample in CI. Also removes `ca_file` from the README for custom auth, as it's not needed (and shouldn't be passed - custom authorizors ignore it)
____________
=> Add Cognito connect sample

samples/README.md
When the sample README split was done, it initially was planned to be in sub-folders and the main sample README referred to this. However, after discussion, the decided plan was to have all the samples in the same folder like before but with README files of the same name as the same (example: `pubsub.py` and `pubsub.md`), but the earlier adjustment to the main sample README still referred to the sub-folder solution.
This PR fixes that reference and makes it correct.
Resolves the discussion here: https://github.com/aws/aws-iot-device-sdk-python-v2/discussions/423
_________
=> Fix information in sample README

.builder/actions/crt-ci-test.py, .github/workflows/ci.yml, awsiot/mqtt5_client_builder.py, awsiot/mqtt_connection_builder.py, builder.json, test/test_mqtt.py, test/test_mqtt5.py
* Remove CI jobs that used CRT containers.  We should not use CRT credentials in any way in SDK repos.
* A variety of custom auth bug fixes, primarily around websockets and mqtt311
* Adds full support for signed custom authorizers to both mqtt5 and mqtt311 builders
* Restores unit tests runs when built with aws-crt-builder
* Adds matrix of custom auth tests for both mqtt311 and mqtt5
=> Custom auth fixes, tests, and CI framework

.github/workflows/ci.yml, .github/workflows/ci_run_mqtt5_shared_subscription_cfg.json, samples/README.md, samples/mqtt5_shared_subscription.md, samples/mqtt5_shared_subscription.py
Adds a MQTT5 Shared Subscription sample. Also adds it to CI, where it will just skip if the client becomes disconnected due to a lack of shared subscription support.
_________
=> Mqtt5 shared subscription sample

samples/mqtt5_shared_subscription.md, samples/mqtt5_shared_subscription.py
Makes a quick adjustment to the README of the shared subscription sample to adjust its wording. Also removes the note about MQTT5 being in developer preview from the sample source directly.
________
=> Shared subscription sample readme adjustment

samples/mqtt5_pubsub.py, samples/mqtt5_shared_subscription.py
Fixes a display issue when viewed via the MQTT client on AWS.
_________
=> Adjust MQTT5 samples to output JSON

samples/utils/command_line_utils.py
Was using `username`. Changing to use `authorizer_signature`
=> Update authorizer_signature to use the right cmd name

.github/workflows/ci_run_custom_authorizer_connect_cfg.json, .github/workflows/ci_run_mqtt5_custom_authorizer_cfg.json, .github/workflows/ci_run_mqtt5_custom_authorizer_websockets_cfg.json, .github/workflows/ci_run_mqtt5_pubsub_cfg.json, .github/workflows/ci_run_mqtt5_shared_subscription_cfg.json, .github/workflows/ci_run_pubsub_cfg.json, codebuild/samples/custom-auth-linux.sh, codebuild/samples/pubsub-linux.sh, codebuild/samples/pubsub-mqtt5-linux.sh, samples/basic_connect.py, samples/basic_discovery.py, samples/cognito_connect.py, samples/custom_authorizer_connect.py, samples/fleetprovisioning.py, samples/jobs.py, samples/mqtt5_custom_authorizer_connect.py, samples/mqtt5_pkcs11_connect.py, samples/mqtt5_pubsub.py, samples/mqtt5_shared_subscription.py, samples/pkcs11_connect.py, samples/pubsub.py, samples/shadow.py, samples/utils/command_line_utils.py, samples/websocket_connect.py, samples/windows_cert_connect.py, samples/x509_connect.py
Refactors samples not to rely on `cmdUtils` to setup MQTT clients, to connect/disconnect for connect samples, and overall just makes `cmdUtils` go back to command line parsing and nothing more.
Also contains the following minor changes:
* Adjusts all samples to register all command line commands and get the data from said commands in a single function, rather than doing it individually in each sample.
* This also fixed a few minor inconsistencies that slipped through: like `region` being used in a couple samples instead of `signing_region`.
* Fixes possible Cross-SDK repository communication for PubSub by appending UUIDs to topics
_____________
=> Sample and command line refactor

samples/mqtt5_shared_subscription.md, samples/mqtt5_shared_subscription.py
Makes a few minor changes to better fit the AWS docs for shared subscriptions. Also adds more logging and removes some temporary code added for compatibility prior to shared subscription support public release.
________
=> Adjust shared subscription sample to better fit docs

samples/custom_authorizer_connect.py, samples/mqtt5_custom_authorizer_connect.py, samples/utils/command_line_utils.py
Adjusts the custom authorizer samples to allow passing the custom auth token key name and custom auth token value.
_____________
=> Adjust custom auth samples for token key name and token value

.github/workflows/ci.yml, .github/workflows/ci_run_pkcs12_connect_cfg.json, awsiot/mqtt5_client_builder.py, awsiot/mqtt_connection_builder.py, documents/MQTT5_Userguide.md, samples/README.md, samples/pkcs12_connect.md, samples/pkcs12_connect.py, samples/utils/command_line_utils.py
The TLS context has support for PKCS12 for MacOS Devices, but it was never bound out for the MQTT311 or MQTT5 builders, nor did we have a sample for it! This fixes all of that.
_________
=> PKCS12 connect sample

samples/utils/command_line_utils.py
Fixes the Greengrass sample incorrectly requiring `--endpoint` to be passed. Also brings back `--region` instead of `--signing_region` for backwards compatibility with the Greengrass docs.
_________
=> Fix basic discovery sample command line input

samples/basic_discovery.py, samples/utils/command_line_utils.py
Fixes that `cliendId` was not being passed nor read from the command line. ~~Now it is properly registered and assigned as expected.~~ Now it uses the thing name as the cliend ID.
__________
=> Greengrass discovery fix two

awsiot/greengrasscoreipc/clientv2.py, awsiot/greengrasscoreipc/model.py, test/echotestrpc/model.py
This change adds new fields to the IPC operations for sending and receiving MQTT messages with IoT Core in order to support MQTT 5 functionality.
Documentation on the models is also now present in the generated code.
=> Greengrass IPC update including MQTT 5 models

.github/workflows/ci.yml, .github/workflows/ci_run_greengrass_discovery_cfg.json, samples/basic_discovery.py, utils/run_sample_ci.py
Adds running the Greengrass discovery sample in CI, set to only print the discovery information, like how it used to be tested. This helps ensure the sample always runs as expected and increases testing coverage.
Also slightly modifies the sample to not show the discovery results when running in CI, just to hide a bit of information that we might not want to show.
_________
=> Run greengrass discovery in ci

awsiot/mqtt_connection_builder.py, samples/pubsub.py
* Add extra mqtt3 callbacks (`on_connection_success`, `on_connection_failure`, `on_connection_closed`)
=> Add extra mqtt3 callbacks

README.md
Bring in PR https://github.com/aws/aws-iot-device-sdk-python-v2/pull/472 
=> Update the instructions for building from source in README.md 

awsiot/greengrasscoreipc/client.py, awsiot/greengrasscoreipc/clientv2.py, awsiot/greengrasscoreipc/model.py
=> Update model and client for GG 2.11

documents/FAQ.md
Added note about blocking in a callback to FAQ
=> Add to FAQ about blocking in a callback

samples/websocket_connect.md
Correct the AWS environment variable from AWS_SECRET_ACCESS to AWS_SECRET_ACCESS_KEY
=> Doc: fix aws_secret_access env variable

.github/workflows/ci.yml, .github/workflows/ci_run_mqtt5_fleet_provisioning_cfg.json, .github/workflows/ci_run_mqtt5_jobs_cfg.json, .github/workflows/ci_run_mqtt5_shadow_cfg.json, awsiot/__init__.py, codebuild/samples/shadow-linux.sh, samples/README.md, samples/fleetprovisioning_mqtt5.md, samples/fleetprovisioning_mqtt5.py, samples/jobs_mqtt5.md, samples/jobs_mqtt5.py, samples/shadow_mqtt5.md, samples/shadow_mqtt5.py, setup.py
Added service client sample for Shadow, Jobs, and Fleet provisioning. The samples are based on Mqtt311 versions. 
=> Mqtt5 Service Client

.github/workflows/ci_run_custom_authorizer_connect_cfg.json, .github/workflows/ci_run_mqtt5_custom_authorizer_cfg.json, .github/workflows/ci_run_mqtt5_custom_authorizer_websockets_cfg.json, codebuild/samples/custom-auth-linux.sh, samples/custom_authorizer_connect.md, samples/mqtt5_custom_authorizer_connect.md, samples/mqtt5_custom_authorizer_connect.py, samples/utils/command_line_utils.py
* remove mtls and sigv4 parameters from custom auth samples
* update readmes to explain relevant command line parameters
=> Cleanup custom auth samples, improve associated sample readmes

awsiot/mqtt5_client_builder.py, setup.py
=> Topic aliasing options to mqtt5 client builder

.github/workflows/ci.yml, awsiot/mqtt5_client_builder.py, awsiot/mqtt_connection_builder.py, test/test_mqtt.py, test/test_mqtt5.py
* Conditional uri encoding of custom auth signature value
=> Custom auth polish

setup.py
Issue: https://github.com/awslabs/aws-c-io/issues/576
=> update awscrt, which now supports 32bit VSOCK ports

awsiot/mqtt5_client_builder.py
Add note to keep_alive_interval_sec and its relation to ping_timeout_ms
=> add note about keep alive and relation to ping timeout

documents/MQTT5_Userguide.md, samples/README.md, samples/mqtt5_pubsub.md
Prioritize MQTT5 Samples in Samples Readme
=> prioritize mqtt5 samples

documents/MQTT5_Userguide.md, samples/mqtt5_pubsub.md
=> Fix variable names in docs

.github/workflows/closed-issue-message.yml, .github/workflows/stale-issue.yml
We received some customer feedback that our closed issue message is too loud and too full of emoji, and our stale issue timings are too strict, especially on holidays and weekends. This PR corrects both of these issues.
=> Minor GitHub workflow changes

documents/MQTT5_Userguide.md, samples/mqtt5_pubsub.md
add windows certificate code snippet to the mqtt5 userguide
=> add windows cert snippet to userguide

.github/workflows/ci.yml, samples/pubsub.py, utils/run_sample_ci.py
=> Fix windows certificate store test

awsiot/greengrasscoreipc/__init__.py, awsiot/greengrasscoreipc/client.py, awsiot/greengrasscoreipc/clientv2.py
https://github.com/aws/aws-iot-device-sdk-python-v2/issues/521
=> Close notice in Greengrass IPC client documentation

.github/workflows/ci.yml, setup.py
=> Bump CRT version

awsiot/mqtt5_client_builder.py
Fixes kwargs being passed as a single object rather than being unpacked when passed as an argument.
=> Fix kwargs in mqtt5 default builder not being unpacked correctly

setup.py
=> update CRT to 0.23.5

test/test_mqtt.py, test/test_mqtt5.py, test/test_samples.py
=> Fix Skipped Tests

.github/workflows/release.yml
Ubuntu 20.04, which currently is used for release pipeline, is not available anymore.
Use Ubuntu 22.04.
=> Use ubuntu 22.04 for releases

.github/workflows/ci.yml, README.md, builder.json, documents/PREREQUISITES.md, setup.py
=> Raise minimum Python version to 3.8

.github/workflows/ci.yml
[Recent update](https://github.com/actions/runner-images/releases/tag/macos-15-arm64%2F20250830.2281)  of GitHub runner image for macOS causes [CI failures](https://github.com/aws/aws-iot-device-sdk-python-v2/actions/runs/17471271617/job/49620060420)
Updating aws-crt-builder (specifically, https://github.com/awslabs/aws-crt-builder/pull/323 is needed) resolves the issue.
=> Update CRT builder

documents/MQTT5_Userguide.md, samples/README.md, samples/mqtt/mqtt5_aws_websocket.md, samples/mqtt/mqtt5_custom_auth.md, samples/mqtt/mqtt5_x509.md
Remove errant characters in various README files.
Fix some documentation links.
=> Insignificant documentation fix
