aws/aws-iot-device-sdk-python-v2

README.md
awsiot/__init__.py
awsiot/iotjobs.py
samples/jobs.py
samples/shadow.py

output of sample looks like:
```
Connecting to a1kgl8dq36ysyu-ats.iot.us-west-2.amazonaws.com on port 8883...
Connect completed with code: 0
Subscribing to Next Changed events...
Subscribing to Start responses...
Subscribing to Update responses...
Trying to start the next job...
Publishing request to start next job...
Published request to start the next job.
Request to start next job was accepted. job_id:jobs01 job_document:{'operation': 'hello'}
Starting local work on job...
Done working on job.
Publishing request to update job status to SUCCEEDED...
Published request to update job.
Request to update job was accepted.
Received Next Job Execution Changed event: None. Waiting for further jobs...
```
By submitting this pull request, I confirm that my contribution is made under the terms of …

jobs sample

---

README.md

Update README to specify aws-crt-python version

---

awsiot/__init__.py
awsiot/iotjobs.py
awsiot/iotshadow.py
samples/jobs.py
samples/shadow.py

Generated QoS into service APIs and updated samples

---

README.md
awsiot/__init__.py
awsiot/greengrass_discovery.py
awsiot/iotjobs.py
awsiot/iotshadow.py
codebuild/install_and_run_samples.yml
samples/basic_discovery.py
samples/jobs.py
samples/pubsub.py
samples/shadow.py
setup.py

Green grass support

---

continuous-delivery/publish_to_prod_pypi.yml
continuous-delivery/publish_to_test_pypi.yml

Fixed cut statement in download.

---

continuous-delivery/test_test_pypi.yml
setup.py

Fix test pypi installation script.

---

continuous-delivery/test_prod_pypi.yml
continuous-delivery/test_test_pypi.yml
continuous-delivery/test_version_exists

Fixed up CD pipeline to work from github releases instead of annotated tags

---

awsiot/__init__.py
awsiot/greengrass_discovery.py
samples/basic_discovery.py
samples/jobs.py
samples/pubsub.py
samples/shadow.py
setup.py

Fixes:
- on_connection_resumed callbacks had misnamed argument
- GG Discovery had python-2 incompatible str->bytes conversion
Polish:
- add kwargs to appropriate callbacks
- misc

Minor fixes and polish

---

setup.py

bump version to 1.0.5

---

.github/ISSUE_TEMPLATE/---bug-report.md
.github/ISSUE_TEMPLATE/---feature-request.md
.github/ISSUE_TEMPLATE/---questions---help.md

New issue template

---

awsiot/greengrass_discovery.py
setup.py

Note: this build won't pass until the crt pypi package is deployed

Updated to use the new http stream activate api.

---

setup.py

Update aws-crt-python to get mqtt-reconnect-timeout fixes

---

awsiot/iotjobs.py

Add missing parameter to UpdateJobExecution

Add missing parameter to UpdateJobExecution

---

.github/ISSUE_TEMPLATE/---bug-report.md
.github/workflows/stale-issue.yml

NA
- Added message as part of the bug and guidance template to address ats type endpoint.
- Changed stale action to run every hour instead of 15 mins.

Tempalte and stale action update

---

continuous-delivery/publish_to_prod_pypi.yml
continuous-delivery/publish_to_test_pypi.yml
setup.py

Always set the package version to match the git tag when publishing

---

continuous-delivery/test_version_exists

Don't check setup.py anymore

---

continuous-delivery/publish_to_prod_pypi.yml
continuous-delivery/publish_to_test_pypi.yml

CD: get into the source dir before using git

---

awsiot/iotjobs.py
awsiot/iotshadow.py

NamedShadow import

---

setup.py

Update to latest awscrt

---

README.md

topic -> topicfilter in subscribe patterns

Correct provisioning sample policy template

---

NOTICE
awsiot/__init__.py
awsiot/greengrass_discovery.py
awsiot/iotidentity.py
awsiot/iotjobs.py
awsiot/iotshadow.py
samples/basic_discovery.py
samples/fleetprovisioning.py
samples/jobs.py
samples/pubsub.py
samples/shadow.py
setup.py
test/__init__.py
test/test_samples.py

Update license to remove Copyright year.

---

setup.py

https://github.com/aws/aws-iot-device-sdk-python-v2/issues/86
https://github.com/aws/aws-iot-device-sdk-python-v2/issues/62
New crt version with multiple bug fixes for issues

Update crt dependency for bug fixes

---

setup.py

udpate awscrt to 0.6.2

---

setup.py

Updated to v0.9.3 of Python CRT

---

continuous-delivery/publish_to_prod_pypi.yml
continuous-delivery/publish_to_test_pypi.yml

fixed py package installs in CD

---

continuous-delivery/wait-for-pypi.py
setup.py

0.9.3 was missing wheels for several platforms

update awscrt to 0.9.10

---

awsiot/eventstreamrpc.py
awsiot/greengrasscoreipc/client.py
awsiot/greengrasscoreipc/model.py
setup.py
test/echotestrpc/client.py
test/echotestrpc/model.py
test/test_rpc.py

* New Greengrass IPC client added

New Greengrass IPC client added

---

CONTRIBUTING.md

find/replace: master->main

---

awsiot/eventstreamrpc.py
test/test_rpc.py

Mostly just stressing the error-handling code. No bugs found.

Add more eventstreamrpc tests

---

setup.py

n/a
Add license definition to setup.py

define the license so 'pip3 show' shows the license

---

setup.py

latest-awscrt

---

setup.py

* Depending on a new version of awscrt to get event stream RPC fix

Updating dependency to pick up event stream RPC client fix.

---

awsiot/greengrasscoreipc/client.py
awsiot/greengrasscoreipc/model.py

Reverts aws/aws-iot-device-sdk-python-v2#165

Revert "update GG codengen module"

---

setup.py

Fixes installs from source.
Fixes raspberry pi installs.

Update awscrt to 0.11.8

---

setup.py

* More validation of HTTP/1.1 messages (#273); from aws-crt-python->aws-c-http

Updating aws-crt-python submodule for bug fixes.

---

README.md
awsiot/__init__.py
builder.json
continuous-delivery/publish_to_prod_pypi.yml
continuous-delivery/publish_to_test_pypi.yml
setup.py

remove support of 3.5 as awscrt did

---

awsiot/greengrasscoreipc/client.py
awsiot/greengrasscoreipc/model.py
setup.py
test/echotestrpc/model.py

Updating Greengrass client

---

setup.py

Fix Mac SNI check with overridden root CA

---

codebuild/samples/linux-smoke-tests.yml
codebuild/samples/pubsub-linux.sh
codebuild/samples/setup-linux.sh

Pubsub in ci

---

setup.py

Dependency update to support Tls on Windows in a userless configuration

---

awsiot/greengrasscoreipc/client.py
awsiot/greengrasscoreipc/model.py
test/echotestrpc/client.py
test/echotestrpc/model.py

windowsUser addition

---

setup.py

Update CRT to pull in ECS credentials provider fix

---

PREREQUISITES.md
README.md

Updated README build from source section, as well as updating the prerequisites to use latest install instructions from C++ repo
_________

Readme install instructions update

---

.github/workflows/closed-issue-message.yml
.github/workflows/docs.yml
.github/workflows/stale-issue.yml

because actions in this repo no longer have write permission by default.

Give explicit permissions to Github actions

---

docsrc/conf.py
setup.py

Updates to use the latest CRT release.

Update to use latest CRT

---

setup.py

- Fix the mishandling of error message that "The Unknown Error Code" is being reported as "AWS_ERROR_OOM"
- Fix connection infinite loop

update crt to 0.14.3

---

setup.py

Update to the latest CRT release to get the `Python out of memory error` fix.
________

Update to latest CRT

---

setup.py

* Binding for Cognito credentials provider
* Eventstream rpc client update to fix crash-causing race condition (https://github.com/awslabs/aws-crt-python/issues/383)

CRT update to pull in Cognito binding and eventstream crash fix

---

setup.py

Updates sub-modules to get latest fixes and improvements.
____________

Update submodules to latest release

---

README.md

AutoTag PR for v1.12.1

---

.github/workflows/release.yml

Forgot a permission in the release yaml.
__________

Release yaml fix two

---

README.md

AutoTag PR for v1.12.2

---

README.md

AutoTag PR for v1.12.3

---

setup.py

Fixing a low severity issue with parsing certificate Common Name (CN)

Fixing a low severity issue with parsing certificate Common Name (CN)

---

setup.py

Potential fix for https://github.com/aws/aws-iot-device-sdk-python-v2/issues/394

CRT update to pull in min reconnect delay fix

---

setup.py

Update CRT dependency to pull in DNS behavior improvements

---

README.md

AutoTag PR for v1.14.0

---

setup.py

Updates the Python CRT to the latest release. Will add MQTT311 shared subscription support.
______________

Use latest CRT release

---

README.md

AutoTag PR for v1.14.1

---

samples/utils/command_line_utils.py

* check two commands for one assignment in samples

check two commands for one assignment

---

README.md

AutoTag PR for v1.15.0

---

.github/workflows/stale-issue.yml

update time to ancient

---

setup.py

* Update CRT to resolve raspberry pi issue

Update CRT to resolve raspberry pi issue

---

README.md

AutoTag PR for v1.15.1

---

setup.py

Bring in the fix at: https://github.com/awslabs/aws-crt-python/pull/478
Fixed issue reported at: https://github.com/aws/aws-iot-device-sdk-python-v2/issues/462

Update awscrt to fix puback bug

---

README.md

AutoTag PR for v1.15.2

---

README.md

AutoTag PR for v1.15.3

---

setup.py

update aws-crt-python to 0.16.21

---

README.md

AutoTag PR for v1.15.4

---

setup.py

Update CRT to pull in eventstream RPC crash fix

---

README.md

AutoTag PR for v1.16.0

---

setup.py

Update CRT to pull in MQTT311 packet framing fix

---

README.md

AutoTag PR for v1.17.0

---

setup.py

Update mqtt submodule to pull in 311 ping fix and 5 validation relaxation for IoT Core

Mqtt Updates

---

README.md

AutoTag PR for v1.18.0

---

README.md

AutoTag PR for v1.19.0

---

awsiot/__init__.py

Bring in customer PR https://github.com/aws/aws-iot-device-sdk-python-v2/pull/511
Fix the assertion in service client constructor. 

Fix MQTT connection argument validation

---

test/test_mqtt.py

Use unsigned authorizer for unsigned custom auth test

---

README.md
documents/FAQ.md

Readme cleanup

---

setup.py

update crt version to latest

---

README.md

AutoTag PR for v1.19.1

---

samples/pubsub.py

Typo in connection failed callback

---

setup.py

Update awscrt to 0.19.17

---

documents/MQTT5_Userguide.md
samples/mqtt5_custom_authorizer_connect.md
samples/mqtt5_pkcs11_connect.md
samples/mqtt5_pubsub.md
samples/mqtt5_shared_subscription.md
setup.py

Mqtt5 General Availability

---

README.md

AutoTag PR for v1.20.0

---

.github/workflows/ci.yml
samples/utils/command_line_utils.py
servicetests/test_cases/mqtt3_fleet_provisioning_with_csr_cfg.json
servicetests/test_cases/mqtt5_fleet_provisioning_cfg.json
servicetests/test_cases/mqtt5_fleet_provisioning_with_csr_cfg.json
servicetests/test_cases/test_fleet_provisioning.py
servicetests/tests/FleetProvisioning/fleet_provisioning.py
servicetests/tests/JobsExecution/jobs.py

Fleet Provisioning Service Tests

Fleet Provisioning Service Tests

---

.github/workflows/ci.yml
servicetests/test_cases/test_shadow_update.py
servicetests/tests/ShadowUpdate/shadow_update.py

- Fix race condition.
- Add a small waiting into results checking.

Fix shadow tests

---

README.md

AutoTag PR for v1.21.0

---

README.md

AutoTag PR for v1.21.1

---

documents/MQTT5_Userguide.md

Correct the MQTT5 userguide information on Publish

correct MQTT5 Userguide Publish information

---

awsiot/iotjobs.py
awsiot/iotshadow.py

Update codegen service clients

---

README.md

AutoTag PR for v1.21.2

---

setup.py

Update crt version to v0.20.8

---

README.md

AutoTag PR for v1.21.4

---

README.md

AutoTag PR for v1.21.5

---

.github/workflows/ci.yml

TODO: update the setting to make macos-latest optional.

Add macos-latest as optional CI test image

---

awsiot/greengrasscoreipc/clientv2.py
awsiot/greengrasscoreipc/model.py

Update Greengrass IPC

---

setup.py

Bump CRT version to v0.21.1

---

README.md

AutoTag PR for v1.22.0

---

README.md

AutoTag PR for v1.22.1

---

setup.py

Update awscrt to 0.24.1

---

README.md

AutoTag PR for v1.22.2

---

utils/ci_iot_thing.py

Deleting an IoT thing before its principals are all released was causing CI to fail. Wait for the principals to be released before moving onto deleting.

CI small fix

---

setup.py

Update awscrt 0.24.1 -> 0.27.4

Update awscrt 0.24.1 -> 0.27.4

---

README.md

AutoTag PR for v1.23.0

---

README.md

AutoTag PR for v1.24.0

---

README.md

AutoTag PR for v1.25.0

---

samples/README.md
samples/greengrass/basic_discovery.md
samples/greengrass/ipc_greengrass.md
samples/mqtt/mqtt5_aws_websocket.md
samples/mqtt/mqtt5_custom_auth.md
samples/mqtt/mqtt5_pkcs11_connect.md
samples/mqtt/mqtt5_x509.md
samples/pubsub.md
samples/service_clients/fleet_provisioning_basic.md
samples/service_clients/fleet_provisioning_csr.md
samples/service_clients/jobs.md
samples/service_clients/shadow.md

Add usage disclaimer to sample README

Add usage disclaimer to sample README
